config/routes.rb
SpaceSpotter::Application.routes.draw do
  #splash page
  root "welcome#index"

  #user session info
  get "/login", to: "session#new"
  post "/session", to: "session#create"
  delete "/session", to: "session#destroy"

  #user resources
  resources :users do
    resources :spot_mails
  end

  resources :listings do
    resources :timeslots
  end

  resources :vendors do
    resources :listings, controller: "vendors/listings" do
      resources :timeslots, controller: "vendors/timeslots"
    end
  end

  resources :customers do
    resources :bookings
  end
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  validates :title, presence: true
  validates :description, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip_code, presence: true
  validates :rate, presence: true
  validates_associated :vendor 

  belongs_to :vendor
  has_many :timeslots, dependent: :destroy
  has_many :bookings, through: :timeslots
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def index
    @listings = Listing.all
  end

  def show
    @listing = Listing.find(params[:id])
    @timeslots = Timeslot.where(listing_id: @listing.id)
  end
end

app/controllers/vendors/listings_controller.rb
class Vendors::ListingsController < ApplicationController
  before_action :load_vendor, only: [:index, :show, :edit, :update, :destroy]
  before_action :load_listing, only: [:show, :edit, :update, :destroy]

  def index
    @listings = Vendor.find(session[:user_id]).listings
  end

  def show
    @timeslots = Timeslot.where(listing_id: @listing.id)
  end

  def new
    @vendor = Vendor.find(session[:user_id])
    @listing = Listing.new
  end

  def create
    @vendor = Vendor.find(session[:user_id])
    @listing = Listing.new(listing_params)
    @listing.vendor_id = @vendor.id
    @listing.save
    if @listing.save
      redirect_to vendor_listing_path(@vendor, @listing)
    else
      render(:new)
    end
  end

  def edit 
    @timeslots = Timeslot.where(listing_id: @listing)
  end

  def update
    @listing_update = @listing.update(listing_params)
    if @listing_update
      redirect_to vendor_listing_path(@vendor, @listing)
    else
      render(:edit)
    end
  end

  def destroy
    @listing.destroy
    redirect_to vendor_listings_path
  end

  private

  def load_listing
    @listing = Listing.find(params[:id])
  end

  def load_vendor
    @vendor = Vendor.find(session[:user_id])
  end 

  def listing_params
    params.require(:listing).permit(
      :title,
      :listing_photo_url,
      :description,
      :address,
      :city,
      :state,
      :zip_code,
      :rate
    )
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/index.html.erb
<div class="wrapper">

  <h1>Listings</h1>

  <% @listings.each do | listing | %>
    <div class="listing-item">
      <div class="listing-item-title">
        <%= link_to listing.title, listing_path(listing) %>
      </div>
      <img src="<%= listing.listing_photo_url %>" alt="">
      <div class="right-listing-item">
        
      </div>
    </div>
  <% end %>


</div>

app/views/listings/show.html.erb
<div class="wrapper">

  <h2><%= @listing.title %> - <%= link_to "Book This Listing", listing_timeslots_path(@listing) %></h2>

  <div class="left-column">
    <img class="listing-photo" src="<%= @listing.listing_photo_url %>">

    <p><%= @listing.description %></p>

  </div>

  <div class="right-column">
    <h3>Rate: $<%= @listing.rate %></h3>

    <h3>Location</h3>
    <ul>
      <li><%= @listing.address %></li>
      <li><%= @listing.city %></li>
      <li><%= @listing.state %></li>
    </ul>

    <h3>Availability</h3>
    <ul>

      <% if @timeslots.exists? == false %>

      <li>No Availabilities At This Time</li>

      <% elsif %>

        <% @timeslots.each do |timeslot| %>
          <% if timeslot.booked == true %>
            <li class="listing-timeslot booked"><%= timeslot.date %></li>
          <% else %>
          <li class="listing-timeslot"><%= timeslot.date %> From: <%= timeslot.start_time.strftime(format=' %l:%M %p') %> To: <%= timeslot.stop_time.strftime(format='%l:%M %p') %></li>
          <% end %>

        <% end %>
      <% end %>
    </ul>
  </div>
</div>