config/routes.rb
SpaceSpotter::Application.routes.draw do
  #splash page
  root "welcome#index"

  #user session info
  get "/login", to: "session#new"
  post "/session", to: "session#create"
  delete "/session", to: "session#destroy"

  #user resources
  resources :users do
    resources :spot_mails
  end

  resources :listings do
    resources :timeslots
  end

  resources :vendors do
    resources :listings, controller: "vendors/listings" do
      resources :timeslots, controller: "vendors/timeslots"
    end
  end

  resources :customers do
    resources :bookings
  end
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  validates :title, presence: true
  validates :description, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip_code, presence: true
  validates :rate, presence: true
  validates_associated :vendor 

  belongs_to :vendor
  has_many :timeslots, dependent: :destroy
  has_many :bookings, through: :timeslots
end

app/models/vendor.rb
class Vendor < User
  validates :phone_number, presence: true
  has_many :listings
  has_many :timeslots, through: :listings
  has_many :bookings, through: :timeslots
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def index
    @listings = Listing.all
  end

  def show
    @listing = Listing.find(params[:id])
    @timeslots = Timeslot.where(listing_id: @listing.id)
  end
end

app/controllers/vendors/listings_controller.rb
class Vendors::ListingsController < ApplicationController
  before_action :load_vendor, only: [:index, :show, :edit, :update, :destroy]
  before_action :load_listing, only: [:show, :edit, :update, :destroy]

  def index
    @listings = Vendor.find(session[:user_id]).listings
  end

  def show
    @timeslots = Timeslot.where(listing_id: @listing.id)
  end

  def new
    @vendor = Vendor.find(session[:user_id])
    @listing = Listing.new
  end

  def create
    @vendor = Vendor.find(session[:user_id])
    @listing = Listing.new(listing_params)
    @listing.vendor_id = @vendor.id
    @listing.save
    if @listing.save
      redirect_to vendor_listing_path(@vendor, @listing)
    else
      render(:new)
    end
  end

  def edit 
    @timeslots = Timeslot.where(listing_id: @listing)
  end

  def update
    @listing_update = @listing.update(listing_params)
    if @listing_update
      redirect_to vendor_listing_path(@vendor, @listing)
    else
      render(:edit)
    end
  end

  def destroy
    @listing.destroy
    redirect_to vendor_listings_path
  end

  private

  def load_listing
    @listing = Listing.find(params[:id])
  end

  def load_vendor
    @vendor = Vendor.find(session[:user_id])
  end 

  def listing_params
    params.require(:listing).permit(
      :title,
      :listing_photo_url,
      :description,
      :address,
      :city,
      :state,
      :zip_code,
      :rate
    )
  end
end

app/controllers/vendors/timeslots_controller.rb
class Vendors::TimeslotsController < ApplicationController
  before_action :load_vendor
  before_action :load_listing

  def index
    @timeslots = Timeslot.where(listing_id: params[:listing_id])
  end

  def new
    @timeslot = Timeslot.new
  end

  def create
    @timeslot = Timeslot.new(timeslot_params)
    @timeslot.update(listing_id: @listing.id)
    if @timeslot.save
      redirect_to edit_vendor_listing_path(@vendor, @listing)
    else
      render(:new)
    end
  end

  def show
    @user = Customer.find(session[:user_id])
    @timeslot = Timeslot.find(params[:id])
  end

  def edit
    @timeslot = Timeslot.find(params[:id])
  end

  def update
    @timeslot = Timeslot.find(params[:id])
    @timeslot_update = @timeslot.update(timeslot_params)
    if @timeslot_update
      redirect_to vendor_listing_path(@vendor, @listing)
    else
      render(:edit)
    end
  end

  def destroy
    @timeslot = Timeslot.find(params[:id])
    @timeslot.destroy
    redirect_to vendor_listing_path(@vendor, @listing)
  end

  private 

  def load_vendor
    return @vendor = Vendor.find(session[:user_id])
  end

  def load_listing
    return @listing = Listing.find(params[:listing_id])
  end

  def timeslot_params
    params.require(:timeslot).permit(
      :date,
      :start_time,
      :stop_time
      )
  end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :load_vendor, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, :authorize, only: [:edit, :update, :destroy]

  def new
    @vendor = Vendor.new
  end

  def create
    @vendor = Vendor.new(vendor_params)

    if @vendor.save
      redirect_to vendor_path(@vendor)
    else
      render(:new)
    end
  end

  def show
  end

  def update
    @account_update = @vendor.update(vendor_params)
    if @account_update
      redirect_to vendor_path(@vendor)
    else
      render(:edit)
    end
  end

  def destroy
    @vendor.destroy
    session.destroy
    redirect_to root_path
  end

  private

  def load_vendor
    return @vendor = Vendor.find(params[:id])
  end

  def vendor_params
    params.require(:vendor).permit(
      :first_name, 
      :last_name, 
      :email,
      :username,  
      :password, 
      :password_confirmation,
      :phone_number, 
      :photo_url,
      :address,
      :city,
      :state,
      :bio_text,
      :zip_code,
      :role
    )
  end

  def authenticate
    unless logged_in?
      redirect_to login_path
    end
  end

  def authorize
    unless current_user == @vendor
      redirect_to login_path
    end
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/vendors/listings/_form.html.erb
<h2><%= @listing.id.nil? ? "Create New Listing" : "Update Listing" %></h2>

<div class="left-column">
  <%= form_for @listing, url: [@vendor, @listing] do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %><br>

    <%= f.label :listing_photo_url, "Photo Link" %>
    <%= f.text_field :listing_photo_url %><br>  

    <%= f.label :description %>
    <%= f.text_field :description %><br>

    <%= f.label :address %>
    <%= f.text_field :address %><br>

    <%= f.label :city %>
    <%= f.text_field :city %><br>

    <%= f.label :state %>
    <%= f.text_field :state %><br>

    <%= f.label :zip_code, "Zip Code" %>
    <%= f.text_field :zip_code %><br>

    <%= f.label :rate %>
    <%= f.text_field :rate %><br>

    <%= f.submit @listing.id.nil? ? "Create" : "Save Changes" %>
  <% end %>

</div>

<div class="right-column">
  <% if @listing.id.nil?  %>
  <% else %>
    <h3>Listing Availability</h3>
    <%= link_to "Add New Timeslot", new_vendor_listing_timeslot_path(@vendor, @listing) %>
    <ul>
      <% @timeslots.each do |timeslot| %>
      <li class="listing-timeslot"><%= timeslot.date %> From: <%= timeslot.start_time.strftime(format=' %l:%M %p') %> To: <%= timeslot.stop_time.strftime(format='%l:%M %p') %> - <%= link_to "Update", edit_vendor_listing_timeslot_path(@vendor, @listing, timeslot) %> </li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/vendors/listings/edit.html.erb
<div class="wrapper">
  <%= render "form" %>
</div>

app/views/vendors/listings/index.html.erb
<div class="wrapper">
  <h2><%= @vendor.first_name %>'s Listings</h2>

  <ul>
    <% @listings.each do | listing | %>
      <li><%= link_to listing.title, vendor_listing_path(@vendor, listing) %></a> - <%= link_to "Update Listing", edit_vendor_listing_path(@vendor, listing) %></li>
    <% end %>
  </ul>
</div>

app/views/vendors/listings/new.html.erb
<div class="wrapper">
  <%= render "form" %>
</div>

app/views/vendors/listings/show.html.erb
<div class="wrapper">
  <h2><%= @listing.title %></h2>

  <div class="left-column">
    <img class="listing-photo" src="<%= @listing.listing_photo_url %>">

    <p><%= @listing.description %></p>
    <%= form_tag edit_vendor_listing_path, method: "GET" do %>
      <%= submit_tag "Update Listing" %>
    <% end %>

    <%= form_tag vendor_listing_path, method: "DELETE" do %>
      <%= submit_tag "Delete Listing" %>
    <% end %>

  </div>

  <div class="right-column">
    <h3>Rate: $<%= @listing.rate %></h3>

    <h3>Location</h3>
    <ul>
      <li><%= @listing.address %></li>
      <li><%= @listing.city %></li>
      <li><%= @listing.state %></li>
    </ul>

    <h3>Availability</h3>
    <ul>

      <% if @timeslots.exists? == false %>

      <li>No Availabilities At This Time</li>

      <% elsif %>

        <% @timeslots.each do |timeslot| %>
         
          <li class="listing-timeslot"><%= timeslot.date %> From: <%= timeslot.start_time.strftime(format=' %l:%M %p') %> To: <%= timeslot.stop_time.strftime(format='%l:%M %p') %></li>
     

        <% end %>
      <% end %>
    </ul>
  </div>
</div>