config/routes.rb
SpaceSpotter::Application.routes.draw do
  #splash page
  root "welcome#index"

  #user session info
  get "/login", to: "session#new"
  post "/session", to: "session#create"
  delete "/session", to: "session#destroy"

  #user resources
  resources :users do
    resources :spot_mails
  end

  resources :listings do
    resources :timeslots
  end

  resources :vendors do
    resources :listings, controller: "vendors/listings" do
      resources :timeslots, controller: "vendors/timeslots"
    end
  end

  resources :customers do
    resources :bookings
  end
end

app/models/timeslot.rb
class Timeslot < ActiveRecord::Base
  validates :date, presence: true
  validates :start_time, presence: true
  validates :stop_time, presence: true
  validates_associated :listing
  
  belongs_to :listing

  def format_time
  end
end

app/controllers/timeslots_controller.rb
class TimeslotsController < ApplicationController
  # before_action :load_vendor
  before_action :load_listing

  def index
    @timeslots = Timeslot.where(listing_id: params[:listing_id])
  end

  def show
    @user = Customer.find(session[:user_id])
    @timeslot = Timeslot.find(params[:id])
  end

  def update
    @timeslot = Timeslot.find(params[:id])
    @timeslot_update = @timeslot.update(booked: params[:booked])
    if @timeslot_update
      redirect_to listing_path(@listing)
    else
      render(:edit)
    end
  end

  private 

  def load_listing
    return @listing = Listing.find(params[:listing_id])
  end

  def timeslot_params
    params.require(:timeslot).permit(
      :date,
      :start_time,
      :stop_time
      )
  end
end

app/controllers/vendors/timeslots_controller.rb
class Vendors::TimeslotsController < ApplicationController
  before_action :load_vendor
  before_action :load_listing

  def index
    @timeslots = Timeslot.where(listing_id: params[:listing_id])
  end

  def new
    @timeslot = Timeslot.new
  end

  def create
    @timeslot = Timeslot.new(timeslot_params)
    @timeslot.update(listing_id: @listing.id)
    if @timeslot.save
      redirect_to edit_vendor_listing_path(@vendor, @listing)
    else
      render(:new)
    end
  end

  def show
    @user = Customer.find(session[:user_id])
    @timeslot = Timeslot.find(params[:id])
  end

  def edit
    @timeslot = Timeslot.find(params[:id])
  end

  def update
    @timeslot = Timeslot.find(params[:id])
    @timeslot_update = @timeslot.update(timeslot_params)
    if @timeslot_update
      redirect_to vendor_listing_path(@vendor, @listing)
    else
      render(:edit)
    end
  end

  def destroy
    @timeslot = Timeslot.find(params[:id])
    @timeslot.destroy
    redirect_to vendor_listing_path(@vendor, @listing)
  end

  private 

  def load_vendor
    return @vendor = Vendor.find(session[:user_id])
  end

  def load_listing
    return @listing = Listing.find(params[:listing_id])
  end

  def timeslot_params
    params.require(:timeslot).permit(
      :date,
      :start_time,
      :stop_time
      )
  end
end

app/views/timeslots/_form.html.erb
<h2><%= @timeslot.id.nil? ? "Create New Timeslot" : "Update Timeslot" %></h2>

<div class="left-column">
  <%= form_for [@vendor, @listing, @timeslot] do |f| %>
    <%= f.label :date %>
    <%= f.text_field :date %><br>

    <%= f.label :start_time, "Start Time"%>
    <%= f.text_field :start_time %><br>  

    <%= f.label :stop_time, "Stop Time" %>
    <%= f.text_field :stop_time %><br>

    <%= f.submit @timeslot.id.nil? ? "Add Timeslot" : "Save Changes" %>
  <% end %>

</div>

app/views/timeslots/index.html.erb
<div class="wrapper">

<h2>Availability for <%= @listing.title %></h2>

<p>Please Select Your Desired Timeslot Below:</p>
<ul>

  <% if @timeslots.exists? == false %>

    <li>No Availabilities At This Time</li>

  <% elsif %>

    <% @timeslots.each do |timeslot| %>

    <% if timeslot.booked == false %>
      <li><%= link_to timeslot.date, listing_timeslot_path(@listing, timeslot) %> From: <%= timeslot.start_time.strftime(format=' %l:%M %p') %> To: <%= timeslot.stop_time.strftime(format=' %l:%M %p') %></li>
    <% end %>

    <% end %>
  <% end %>
  </ul>
</div>

app/views/timeslots/show.html.erb
<div class="wrapper">
  <h2>Confirm Booking Request for <%= @listing.title %></h2>

  <p>Book this space on <%= @timeslot.date %> From: <%= @timeslot.start_time.strftime(format=' %l:%M %p') %> To: <%= @timeslot.stop_time.strftime(format=' %l:%M %p') %>?</p>

  <%= form_for [@listing, @timeslot], method: "PUT" do %>
     <%= label_tag "Yes" %>
     <%= radio_button_tag :booked, 'true' %> <br>

     <%= label_tag "No" %>
     <%= radio_button_tag :booked, 'false' %><br>

     <%= submit_tag "Submit" %>
  <% end %>
</div>